### ISSUE TITLE
Rank is missing

### ISSUE THREAD

**Issue by abrudz** [jpellegrini/gnu-apl-refcard#6]
[Rank](https://aplwiki.com/wiki/Rank_(operator)) would be written as `\ddot\circ`.

**Comment by jpellegrini** [comment]
Hi -- sorry for the delay in answering this.

⍤ does not seem to exist in GNU APL... Are you sure you got it to work in GNU APL, and not Dyalog?

**Comment by abrudz** [comment]
I've quite sure:
![image](https://user-images.githubusercontent.com/10961427/125179051-83801580-e1e2-11eb-8e67-4a91cf94fc7c.png)
Compare to Dyalog:
![image](https://user-images.githubusercontent.com/10961427/125179070-a6122e80-e1e2-11eb-9211-f3bcf1e96c25.png)

**Comment by jpellegrini** [comment]
Oh you're right!
I never realized it was there, probably because I copied the wrong unicode char someday or something like that -- so I never used it in GNU APL. Thank you for reporting, and also for letting me know it's there! :)
I'm pushing a commit that will also close this issue.

**Comment by abrudz** [comment]
This is incomprehensible:
![image](https://user-images.githubusercontent.com/10961427/125186440-56535780-e222-11eb-8ad0-537d429c165a.png)
And incomplete:
```apl
      10 20 30+⍤0 1(3 3⍴⍳9)
11 12 13
24 25 26
37 38 39
```
Maybe something like `A f⍤k B` would work?

**Comment by jpellegrini** [comment]
You're right. 
I think it's a lot of information to compress in a single line of a reference card, so the text is not really clear. I'd guess the user will already know most of the concepts, but anyway, you're right about the notation. I'll update it.
