### ISSUE TITLE
Missing Bit-wise Logical Functions ⊤∧, ⊤∨, ⊤⍲, ⊤⍱, T≠, and T=

### ISSUE THREAD

**Issue by abrudz** [jpellegrini/gnu-apl-refcard#9]
See [the documentation](https://www.gnu.org/software/apl/apl.html#Section-3_002e16)

**Comment by jpellegrini** [comment]
Thank you for reporting!
I've just included those; not sure yet if the rendering is the best we could have... I think there may be a nicer way to display them in TeX.

**Comment by jpellegrini** [comment]
Couldn't find a better alternative for those symbols in TeX; this seems to be fine.
